version: '3.9'
services:
  backend:
    image: backend
    ports:
      - "3000:3000"
    extra_hosts:
      - "basededatos:167.99.232.140" 
    hostname: "backend"
    networks:
      - general_network
    deploy:
      mode: replicated
      replicas: 17
      placement:
        constraints: 
          - node.labels.tipo == back
      restart_policy:
        condition: on-failure
  apollo:
    image: apollo
    ports:
      - "4000:4000"
    networks:
      - general_network
    deploy:
      mode: replicated
      replicas: 3
      placement:
        constraints: 
          - node.labels.tipo == manager
      restart_policy:
        condition: on-failure
  frontend:
    image: frontend
    ports:
      - "5000:5000"
    networks:
      - general_network
    deploy:
      mode: replicated
      replicas: 5
      placement:
        constraints:
          - node.labels.tipo == front
      restart_policy:
        condition: on-failure
  visualizer:
    image: dockersamples/visualizer:stable
    ports:
      - "9000:8080"
    stop_grace_period: 1m30s
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
    deploy:
      placement:
        constraints: [node.role == manager]

networks: 
  general_network:
    driver: overlay
    attachable: true
 



