version: '3.8'
services:
  visualizer:
    image: dockersamples/visualizer:stable
    ports:
      - "9000:8080"
    stop_grace_period: 1m30s
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
    deploy:
      placement:
        constraints: 
          - node.labels.tipo == back
 



