version: "3.9"

services:
  web:
    image: 127.0.0.1:5000/stackdemo
    build: .
    ports:
      - "8000:8000"
    deploy:
      mode: replicated
      replicas: 20
      placement:
        constraints: 
          - node.labels.rol == front
  redis:
    image: redis:alpine
    deploy:
      mode: replicated
      replicas: 10
      placement:
        constraints: 
          - node.labels.rol == back
    
